### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-repo_docker#1]
### Type of Report

Review Request

### Actual behaviour

No Review from other developers done.

### Expected behaviour

Role was reviewed and tested from @while-true-do/ansible-developer

**Comment by daniel-schier** [comment]
@donvipre @Cinux90 interested into reviewing?

**Comment by Cinux90** [comment]
A questions from my side. Why got docker removed with the [first tasks](https://github.com/while-true-do/ansible-role-repo_docker/blob/master/tasks/CentOS.yml#L3)? As far as i can see the package in the repo are named as docker-ce. From my point of view its should be part of the administrator to remove docker package.

Of course we can keep the removing of the docker package but then let's set a additional switch and as default we do not remove the package. What do you think about @daniel-wtd ?

**Comment by daniel-schier** [comment]
@Cinux90 unfortunately the distro docker is heavily conflicting with docker-ce. therefore even the guide from docker is recommending to remove all docker packages first.

**Comment by daniel-schier** [comment]
@Cinux90 I have opened #2 to document this in a  better way.

**Comment by Cinux90** [comment]
If that is the case, i guess it's better to remove docker.
Then the role looks fine from my side.
Only one thing to think about:
How about to remove the key if docker-ce repo got removed? It's added every time the repo is installed.

**Comment by daniel-schier** [comment]
@Cinux90 sure, will have a look :+1: I will dig in together with #2 and provide a fix, asap.
